expansion:
  seq2seq_policy:
    type: policy.seq2seq_expansion_strategy.Seq2SeqExpansionStrategy
    model: data/training/liu-et-al/model-v18/model/keras/seq2seq_model.keras
    tokenizer: data/training/liu-et-al/model-v18/tokenizer/model_v18_tokenizer.json
    max_encoder_seq_length: 140
    max_decoder_seq_length: 140
    beam_width: 5
filter:
  uspto: /home/chris-vdb/Computational-Chemistry/aizynthfinder-project/expansion-policies/seq2seq-expansion-policy/data/public-model-data/uspto_filter_model.onnx
stock:
  zinc: /home/chris-vdb/Computational-Chemistry/aizynthfinder-project/expansion-policies/seq2seq-expansion-policy/data/public-model-data/zinc_stock.hdf5