# Seq2Seq Model Architecture
# - No model architectural changes have been made. Model V6 is intended to be a benchmark for a 5 epoch training run
#   for future iterations.
# - The separation of attention, encoder and decoder dimensions from model V5 have been kept, but they have been reduced
#   to 256, 128 and 256 respectively (the halving of the encoder dimensions to account to bidirectionality has been kept
#   from model V5).
# - Units have also been reduced to 256
# - The reduction in epochs, as well as attention, encoder and decoder dimensions is to reduce training time. Optimal
#   future model will have these all increased.
#
# Training run metrics:
#   - Epochs: 5
#
#   - Train Loss (Smoothed): 0.623
#   - Train Accuracy (Smoothed): 0.514
#
#   - Validation Loss (Smoothed): 0.536
#   - Validation Accuracy (Smoothed): 0.537
#
#   - Test Loss (Smoothed): 0.417
#   - Test Accuracy (Smoothed): 0.570

# Data Configuration and Hyperparameters
data:
  products_file: 'data/preprocessed/pande-et-al/products_smiles'
  reactants_file: 'data/preprocessed/pande-et-al/reactants_smiles'
  products_valid_file: 'data/preprocessed/pande-et-al/validation_products_smiles'
  reactants_valid_file: 'data/preprocessed/pande-et-al/validation_reactants_smiles'
  tokenizer_save_path: 'data/training/pande-et-al/model-v6/tokenizer/model_v6_tokenizer.json'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_size: 0.3
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  attention_dim: 256
  encoder_embedding_dim: 128
  decoder_embedding_dim: 256
  units: 256
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 5
  patience: 5
  model_save_path: 'data/training/pande-et-al/model-v6/model'
  log_dir: 'logs/pande-et-al/model-v6'
  checkpoint_dir: 'data/training/pande-et-al/model-v6/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592