# Seq2Seq Model Architecture

# Epochs: 100

# Data Configuration and Hyperparameters
data:
  products_file: '../data/preprocessed/liu-et-al/products_smiles'
  reactants_file: '../data/preprocessed/liu-et-al/reactants_smiles'
  tokenizer_save_path: '../data/training/liu-et-al/model-v29/tokenizer/model_v29_tokenizer.json'
  logger_path: '../var/log/liu-et-al/model-v29/model-v29.log'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_split: 0.1
  validation_split: 0.1
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  attention_dim: 256
  encoder_embedding_dim: 256
  decoder_embedding_dim: 256
  units: 256
  encoder_num_layers: 2
  decoder_num_layers: 4
  beam_width: 5
  weight_decay: null
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 100
  patience: 5
  reverse_tokenized_input_sequence: True
  model_save_path: '../data/training/liu-et-al/model-v29/model/saved_model'
  model_save_dir: '../data/training/liu-et-al/model-v29/model'
  valid_metrics_dir: '../data/training/liu-et-al/model-v29/validation-metrics'
  test_metrics_dir: '../data/training/liu-et-al/model-v29/testing-metrics'
  tensorboard_dir: '../data/training/liu-et-al/model-v29/tensorboard'
  log_dir: '../var/log/liu-et-al/model-v29'
  checkpoint_dir: '../data/training/liu-et-al/model-v29/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592