# Seq2Seq Model Architecture
# - Use Residual Connections:
#	- Add residual (skip) connections between the LSTM layers in both the encoder and decoder to facilitate gradient
#     flow and allow the model to learn identity mappings more easily.
#	- In theory this helps in training deeper networks by mitigating vanishing gradient problems.
# - Improvement in both accuracy and loss in train, validation and test.
#
# Training run metrics:
#   - Epochs: 5
#
#   - Train Loss (Smoothed): 0.445
#   - Train Accuracy (Smoothed): 0.600
#
#   - Validation Loss (Smoothed): 0.365
#   - Validation Accuracy (Smoothed): 0.617
#
#   - Test Loss (Smoothed): 0.300
#   - Test Accuracy (Smoothed): 0.634

# Data Configuration and Hyperparameters
data:
  products_file: 'data/preprocessed/pande-et-al/products_smiles'
  reactants_file: 'data/preprocessed/pande-et-al/reactants_smiles'
  products_valid_file: 'data/preprocessed/pande-et-al/validation_products_smiles'
  reactants_valid_file: 'data/preprocessed/pande-et-al/validation_reactants_smiles'
  tokenizer_save_path: 'data/training/pande-et-al/model-v10/tokenizer/model_v10_tokenizer.json'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_size: 0.3
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  attention_dim: 256
  encoder_embedding_dim: 128
  decoder_embedding_dim: 256
  units: 256
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 5
  patience: 5
  model_save_path: 'data/training/pande-et-al/model-v10/model'
  log_dir: 'logs/pande-et-al/model-v10'
  checkpoint_dir: 'data/training/pande-et-al/model-v10/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592