# Seq2Seq Model Architecture
# - Incorporate Layer Normalisation:
#     - Layer normalisation helps stabilize and accelerate training by normalizing the inputs across the features.
#       This is particularly beneficial in recurrent neural networks like LSTMs, where it can mitigate issues related
#       to exploding or vanishing gradients.
# - Significant improvement in training, validation and test accuracy and loss metrics.
#
# Training run metrics:
#   - Epochs: 5
#
#   - Train Loss (Smoothed): 0.332
#   - Train Accuracy (Smoothed): 0.627
#
#   - Validation Loss (Smoothed): 0.260
#   - Validation Accuracy (Smoothed): 0.644
#
#   - Test Loss (Smoothed): 0.216
#   - Test Accuracy (Smoothed): 0.656

# Data Configuration and Hyperparameters
data:
  products_file: 'data/preprocessed/liu-et-al/products_smiles'
  reactants_file: 'data/preprocessed/liu-et-al/reactants_smiles'
  products_valid_file: 'data/preprocessed/liu-et-al/validation_products_smiles'
  reactants_valid_file: 'data/preprocessed/liu-et-al/validation_reactants_smiles'
  tokenizer_save_path: 'data/training/liu-et-al/model-v11/tokenizer/model_v11_tokenizer.json'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_size: 0.3
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  attention_dim: 256
  encoder_embedding_dim: 128
  decoder_embedding_dim: 256
  units: 256
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 5
  patience: 5
  model_save_path: 'data/training/liu-et-al/model-v11/model'
  test_metrics_dir: 'data/training/liu-et-al/model-v11/evaluate'
  log_dir: 'logs/liu-et-al/model-v11'
  checkpoint_dir: 'data/training/liu-et-al/model-v11/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592