# Seq2Seq Model Architecture
#
# - Add attention dimension functionality to BahdanauAttention mechanism (no change as same as units, just allows
#   decouples attention dimension and units for flexibility for future adjustment).
# - Regularization with Weight Decay:
#	- Weight decay, implemented via L2 regularization, adds a penalty to the loss function proportional to the
#     squared magnitude of the weights. This discourages the model from learning excessively large weights,
#     which can help prevent overfitting.
#
# Training run metrics:
#   - Epochs: 5
#
#   - Train Loss (Smoothed): 0.369
#   - Train Accuracy (Smoothed): 0.625
#
#   - Validation Loss (Smoothed): 0.296
#   - Validation Accuracy (Smoothed): 0.642
#
#   - Test Loss (Smoothed): 0.244
#   - Test Accuracy (Smoothed): 0.655

# Data Configuration and Hyperparameters
data:
  products_file: 'data/preprocessed/liu-et-al/products_smiles'
  reactants_file: 'data/preprocessed/liu-et-al/reactants_smiles'
  products_valid_file: 'data/preprocessed/liu-et-al/validation_products_smiles'
  reactants_valid_file: 'data/preprocessed/liu-et-al/validation_reactants_smiles'
  tokenizer_save_path: 'data/training/liu-et-al/model-v12/tokenizer/model_v12_tokenizer.json'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_size: 0.3
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  attention_dim: 256
  encoder_embedding_dim: 128
  decoder_embedding_dim: 256
  units: 256
  weight_decay: 1.0e-5
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 5
  patience: 5
  model_save_path: 'data/training/liu-et-al/model-v12/model'
  test_metrics_dir: 'data/training/liu-et-al/model-v12/evaluate'
  log_dir: 'logs/liu-et-al/model-v12'
  checkpoint_dir: 'data/training/liu-et-al/model-v12/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592