# Seq2Seq Model Architecture
# - Encoder, decoder and attention mechanism logic has been refactored to improve efficiency and maintainability.
# - This has brought about an improvement in model performance.
# - This could be for a variety of reasons, including:
#     1. Enhanced efficiency leading to better training within the same number of epochs
#     2. Enhanced efficiency reducing computational overhead, reducing time per batch and potentially allowing the
#        optimizer to process more batches within each epoch.
#     3. Enhanced efficiency improving hardware utilization.
#     4. Reduction in code complexity and streamlining may have resolved a previously unidentified bug.
#
# Training run metrics:
#   - Epochs: 5
#
#   - Train Loss (Smoothed): 0.450
#   - Train Accuracy (Smoothed): 0.561
#
#   - Validation Loss (Smoothed): 0.388
#   - Validation Accuracy (Smoothed): 0.577
#
#   - Test Loss (Smoothed): 0.313
#   - Test Accuracy (Smoothed): 0.599



# Data Configuration and Hyperparameters
data:
  products_file: 'data/preprocessed/pande-et-al/products_smiles'
  reactants_file: 'data/preprocessed/pande-et-al/reactants_smiles'
  products_valid_file: 'data/preprocessed/pande-et-al/validation_products_smiles'
  reactants_valid_file: 'data/preprocessed/pande-et-al/validation_reactants_smiles'
  tokenizer_save_path: 'data/training/pande-et-al/model-v7/tokenizer/model_v7_tokenizer.json'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_size: 0.3
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  attention_dim: 256
  encoder_embedding_dim: 128
  decoder_embedding_dim: 256
  units: 256
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 5
  patience: 5
  model_save_path: 'data/training/pande-et-al/model-v7/model'
  log_dir: 'logs/pande-et-al/model-v7'
  checkpoint_dir: 'data/training/pande-et-al/model-v7/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592