# Seq2Seq Model Architecture
# - Identical architecture to model V2, except for reduced layers in encoder and decoder:
#   * Encoder: Single Layer Bidirectional LSTM encoder with segregated Dropout layer.
#   * Decoder: Single Layer LSTM decoder with segregated Dropout layer.

# Data Configuration and Hyperparameters
data:
  products_file: 'data/processed/pande-et-al/products_smiles'
  reactants_file: 'data/processed/pande-et-al/reactants_smiles'
  products_valid_file: 'data/processed/pande-et-al/validation_products_smiles'
  reactants_valid_file: 'data/processed/pande-et-al/validation_reactants_smiles'
  tokenizer_save_path: 'data/training/pande-et-al/model-v3/tokenizer/model_v3_tokenizer.json'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_size: 0.3
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  embedding_dim: 256
  units: 256
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 10
  patience: 5
  model_save_path: 'data/training/pande-et-al/model-v3/model'
  log_dir: 'logs/pande-et-al/model-v3'
  checkpoint_dir: 'data/training/pande-et-al/model-v3/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592