# Seq2Seq Model Architecture
# - Model architecture mostly the same Model V1. The only changes were made in the decoder and callbacks:
#     * Encoder: Encoder logic refactored to ensure that the encoder mask is passed to the encoder LSTM layers.
#                Additionally, layers are now defined separately instead of sequentially for clarity.
#     * Decoder: Decoder logic refactored to ensure that the decoder mask is passed to the decoder LSTM layers.
#     * Learning Rate Scheduler: A learning rate scheduler callback has been added.
#
# Training run metrics:
#   - Train Loss (Smoothed): 0.043
#   - Train Accuracy (Smoothed): 0.342
#   - Validation Loss (Smoothed): 0.042
#   - Validation Accuracy (Smoothed): 0.343
#   - Test Loss (Smoothed):
#   - Test Accuracy (Smoothed):

# Data Configuration and Hyperparameters
data:
  products_file: 'data/preprocessed/pande-et-al/products_smiles'
  reactants_file: 'data/preprocessed/pande-et-al/reactants_smiles'
  products_valid_file: 'data/preprocessed/pande-et-al/validation_products_smiles'
  reactants_valid_file: 'data/preprocessed/pande-et-al/validation_reactants_smiles'
  tokenizer_save_path: 'data/training/pande-et-al/model-v2/tokenizer/model_v2_tokenizer.json'
  max_encoder_seq_length: 140
  max_decoder_seq_length: 140
  batch_size: 32
  test_size: 0.3
  random_state: 4

# Model Configuration and Hyperparameters
model:
  input_vocab_size: null  # To be set dynamically based on tokenizer
  output_vocab_size: null  # To be set dynamically based on tokenizer
  embedding_dim: 256
  units: 256
  dropout_rate: 0.2
  learning_rate: 0.0001
  metrics: ['accuracy']

# Training Configuration and Hyperparameters
training:
  epochs: 10
  patience: 5
  model_save_path: 'data/training/pande-et-al/model-v2/model'
  log_dir: 'logs/pande-et-al/model-v2'
  checkpoint_dir: 'data/training/pande-et-al/model-v2/checkpoints'
  num_samples: null # Number of samples to use for debugging model

# Environment Configuration
env:
  determinism:
    python_seed: "44478977"
    random_seed: 440651
    numpy_seed: 110789
    tf_seed: 61592